### ISSUE TITLE
Error in Excel 2016 Version 1705 Build8201

### ISSUE THREAD

**Issue by ApophisAlpha** [OlapPivotTableExtensions/OlapPivotTableExtensions#1]
PivotTable Extension error when trying to filter Pivot table. Extension was working correctly in Excel 2016 Version 1609, auto-updated yesterday to 1705. I've tried 'Repair' install on the PivotTableExtension V0.9.0, and re-registered Extension in Excel, no change. x64bit. Pivot Table is connected to Excel Power Pivot data model

![image](https://user-images.githubusercontent.com/32511261/31170541-5384d4ea-a8f4-11e7-88f7-29e175783ada.png)

**Comment by furmangg** [comment]
Thanks for reporting. I'm on 16.0.8528.2084 (Version 1709) and can't reproduce the issue.

What all do you have installed on the VM? SSAS? What versions?

**Comment by ApophisAlpha** [comment]
Many thanks for this tool, and for the quick response!

I've used DAX Studio Checker to expose my environment, output below. I notice I may have a problem with some libraries. Do you think the "Warning" below could be responsible for my issue?

Checking Operating System
=======================
OSCaption       = Microsoft Windows 7 Professional 
OSVersion       = 6.1.7601
OSArchitecture  = 64-bit
VisibleMemoryGB = 15.91
FreeMemoryGB    = 6.72

Culture Name              = en-GB
Culture DisplayName       = English (United Kingdom)
Culture EnglishName       = English (United Kingdom)
Culture 2-Letter ISO Name = en
Culture DecimalSeparator  = .
Culture GroupSeparator    = ,
Culture CurrencySymbol    = £
Culture ShortDatePattern  = dd/MM/yyyy
Checking .Net Framework
=======================
v2.0.50727 -> 2.0.50727.5420
v2.0.50727\1033 -> 2.0.50727.5420
v3.0 -> 3.0.30729.5420
v3.0\Setup -> 3.0.30729.5420
v3.0\Setup\1033 -> 3.0.30729.5420
v3.0\Setup\Windows Communication Foundation -> 3.0.4506.5420
v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.5011
v3.5 -> 3.5.30729.5420
v3.5\1033 -> 3.5.30729.5420
v4\Client -> 4.6.01055
v4\Client\1033 -> 4.6.01055
v4\Full -> 4.6.01055
v4\Full\1033 -> 4.6.01055
v4.0\Client -> 4.0.0.0

Checking AMO
=======================
PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
Processing DaxStudio.exe.config file...
Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
Bindings Found: 9
AMO : 14.0.0.0
ADOMD : 14.0.0.0

Checking Excel Add-in
=======================
Detected Excel Version: 16 - Excel_v16
Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
Excel Architecture: x64

DAX Studio Excel Add-in Registry keys
   Description: Dax Studio Excel Add-In
   FriendlyName: Dax Studio Excel Add-In
   Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
   LoadBehavior: 3

Checking for Excel 2010 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2013 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2016 Disabled Add-ins
  PASS > No Disabled items found.

Attempting to load Excel Add-in: 
  PASS > Loaded Excel Add-in: DaxStudio, Version=2.7.0.97, Culture=neutral, PublicKeyToken=null

Checking VSTO Configuration
Architecture: x64
  v4
    Version 10.0.60301
    Install 1
    InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
  v4M
    VSTOMFeature_UNM 1
    VSTOMFeature_CLR35 1
    VSTOMFeature_CLR40 1

**Comment by furmangg** [comment]
Hmm. I don't think the warning above is the issue. Are you still experiencing this?

**Comment by ApophisAlpha** [comment]
Problem now fixed. Solution:

Reinstalled MS OLEDB SQL2016 msi (part of MS SQL Server 2016 Feature Pack)

Once again, thanks for an awesome, indispensable tool

**Comment by furmangg** [comment]
Great to know. That's for the follow up
