### ISSUE TITLE
Oalp 

### ISSUE THREAD

**Issue by gtraub** [OlapPivotTableExtensions/OlapPivotTableExtensions#11]
One of our users is getting the attached error. He is running Excel 2013 and we get the same error both against the olap and tabular cubes. Tried a uninstall/reinstall but it did not help. 

Thanks, for any help you can provide.

![olaperror](https://user-images.githubusercontent.com/16820850/45383688-90630180-b5d1-11e8-9001-6243c8f8ce0b.png)

**Comment by SupSap** [comment]
Hi, I have encountered this problem on two computers too.
Office 2013 32/64 bit.
![image](https://user-images.githubusercontent.com/43239731/45488058-dd2d1080-b768-11e8-81dc-9e6d5fcf2bc3.png)
![image](https://user-images.githubusercontent.com/43239731/45488091-ed44f000-b768-11e8-9c16-022624822845.png)

Please help.
Thank.

**Comment by furmangg** [comment]
Awesome. Thanks for sharing!

**Comment by gtraub** [comment]
Thanks. I will try it out.
