### ISSUE TITLE
Connection Error In Filter List & Search Tabs

### ISSUE THREAD

**Issue by Chriscatx** [OlapPivotTableExtensions/OlapPivotTableExtensions#12]
Hello,

I am trying to use the extensions with Azure AS and get the attached error message. Excel itself is able to connect and works correctly but the OLAP extensions throws the error in both the search and filter list tabs. I tried playing with the connection string but can't get it to work. Any help would be much appreciated.

Thanks,

-Chris
![conn2](https
![conn3a](https://user-images.githubusercontent.com/43277132/45563865-80326880-b803-11e8-92d2-ce129c14853a.png)
![conn1](https://user-images.githubusercontent.com/43277132/45563871-83c5ef80-b803-11e8-8d8e-1ef4b0e6a89a.PNG)

://user-images.githubusercontent.com/43277132/45563582-a4da1080-b802-11e8-8e94-1ca06be9d526.PNG)

**Comment by furmangg** [comment]
Thanks for reporting. I need to do do another release which includes a newer driver which supports Azure Analysis Services. I will update this issue when I do. No ETA yet.

**Comment by peterbud** [comment]
It would be great to have the update with the new drivers. Is there any way I can help?

**Comment by furmangg** [comment]
Thank you all so much for your patience! I'm happy to announce that I've just posted the [0.9.5 release](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases) which adds support for Azure Analysis Services. Please install the latest and let me know if you have troubles.
