### ISSUE TITLE
Tabular model query

### ISSUE THREAD

**Issue by sunilred** [OlapPivotTableExtensions/OlapPivotTableExtensions#14]
Hi. I was wondering if they are plans for OLAPPivotTable Extensions to be extended to work on tabular models? It is great little product and we find it very useful (with Analysis cubes).

Thanks
Sunil

**Comment by furmangg** [comment]
Do you mean to support DAX? I would if Excel APIs supported anything but MDX

Other than that it does work with Tabular models. Let me know if you are hitting something specific.
