### ISSUE TITLE
OLAPPivotTable Extensions for Excel 2016 isn't showing up

### ISSUE THREAD

**Issue by KClarityTC** [OlapPivotTableExtensions/OlapPivotTableExtensions#16]
I have downloaded the most recent add-in. It shows that it is installed, but will not show up in the list of add-ins. I've tried all the steps in the Installation Troubleshooter to no avail. I'm using Office 365 Excel....32 bit. I do not have any other add-ins operating with the exception of the Power Pivot add-in.

**Comment by furmangg** [comment]
Sorry for the delay in replying. Can you go through the troubleshooting steps here, particularly the one where you check if it's an OLAP PivotTable?
https://olappivottableextensions.github.io/Troubleshooting-Installation.html

**Comment by KClarityTC** [comment]
I downloaded 64-bit Excel and can now successfully install OLAP PivotTable Extensions. When trying to use the Disable Autorefresh function, I did receive an error that I had to open up the Power Pivot window. I did so, and Disable Autorefresh now works. Thank you!

**Comment by furmangg** [comment]
Thanks for reporting back. Glad it’s working for you!
