### ISSUE TITLE
Loading time of addin up to 4 minutes

### ISSUE THREAD

**Issue by cbracht** [OlapPivotTableExtensions/OlapPivotTableExtensions#19]
Hello,

for some of our users on Windows 10 with Office 365 ProPlus (Version 1904 or older, 32-Bit) we have a delay ranging from 2 to 4 minutes when the OLAP PivotTable Extensions are loaded (either during Excel startup or when manually activating the addin).

We tried both OLAP PivotTable Extensions versions 0.9.0 and 0.9.5, reinstalling the addin and updating office but couldn't solve the problem. Current Workaround is to only manually enable the addin if it is needed to avoid the delay when starting an Excel instance.

Do you have any ideas or suggestions in how to track this problem down?

Thank you in advance,
cbracht

**Comment by furmangg** [comment]
Yuck. I’m sorry this is causing a delay for you. I certainly don’t experience this delay so let’s see if we can figure out what’s causing it for your install. 

Can you right click on an OLAP PivotTable and open up OLAP PivotTable Extensions then screenshot the About tab and post here as a screenshot?

Can you download the DebugView tool and open it. I’m wondering if it will show any logging for my add-in. For example, does it show a bunch of AssemblyResolve events or something that would occur during the 4 minute delay?

**Comment by furmangg** [comment]
Just guessing at possibilities here. If you disable antivirus temporarily do you still have the delay? I don't have any evidence this would be the issue, but I'm trying to think through what could be the root cause for a loading delay on your computer which is minutes when it loads in one second on my laptop.

**Comment by cbracht** [comment]
Thank you for your fast response. We will try disabling the anti virus as soon as we can get admin rights.

DebugView Screenshot (without admin rights):
![image](https://user-images.githubusercontent.com/1489764/57767988-efea5180-770a-11e9-8f0b-cec7e02157a6.png)
The CursorMonitor Error seems to be not related, this happens when the mouse is moved in the Excel window even when the addin is not loaded.

Olap Pivot Table Extensions About tab:
![image](https://user-images.githubusercontent.com/1489764/57767937-d47f4680-770a-11e9-8f1a-30c599dbfcdf.png)

**Comment by furmangg** [comment]
Keep me posted as you get admin rights and can look at it further. If that doesn't turn up anything I may need to get you a debug build which will log detailed startup times.

**Comment by cbracht** [comment]
We were finally able to deactivate our McAffee Enterprise antivirus solution and the loading delay was gone. I think we will be able to solve this internally. 

Thank you for your support @furmangg and for making our lives a little easier with your addin 👍
