### ISSUE TITLE
Excel 2016 doesn't show the extension

### ISSUE THREAD

**Issue by mshparber** [OlapPivotTableExtensions/OlapPivotTableExtensions#2]
Hello,
I've installed the 0.9.0 but my Excel 2016 doesn't show it anywhere (looked in Disabled Add-ins as well)
Please help
Thank

**Comment by furmangg** [comment]
Sorry for the delay in replying. Busy month. Is this still a problem?

**Comment by mshparber** [comment]
Yes, still don't see it anywhere. Please help
Thank you

**Comment by jeff30075** [comment]
I am also having this problem.  I'm very bummed. Anything you could do to fix quickly would be greatly appreciated.

Thanks!
Jeff

**Comment by furmangg** [comment]
What exact version number of Excel 2016? 32-bit or 64-bit? I haven't been able to reproduce this yet but am looking into it.

**Comment by jeff30075** [comment]
Version 1711 (Build 8730.2122)

32-bit

**Comment by jeff30075** [comment]
Version 1711 (Build 8730.2122) 

32-bit

**Comment by furmangg** [comment]
What's the source of the PivotTable? SSAS? Power Pivot? 

 If you click on the PivotTable then press Alt-F11 then Ctrl-G then paste the following into the Immediate window and press enter: 

 ?ActiveCell.PivotTable.PivotCache().OLAP 

 Does it say True? 

 If not, then you PivotTable is a native PivotTable that's summarizing some table or other data in the spreadsheet or SQL table. You have to have an OLAP PivotTable (that is, one connected to an Analysis Services server or Power Pivot) for my add-in to work.

**Comment by furmangg** [comment]
Just to check, you don't see it here?
![olappivottableextensionsaddininstalled](https://user-images.githubusercontent.com/9261846/34054245-a0e92ed8-e18f-11e7-9d34-dc48bacef7f2.png)

But you do see it installed in Windows Programs list?
![olappivottableextensionsaddremoveprograms](https://user-images.githubusercontent.com/9261846/34054440-9dfff110-e190-11e7-9462-3d7e26b30af6.png)

**Comment by furmangg** [comment]
Do you have Office 2016 installed from a MSI or the Office 365 variety?

**Comment by jeff30075** [comment]
It shows in the add ins:

![image](https://user-images.githubusercontent.com/34559109/34054627-a85d8998-e180-11e7-93d3-03247bade7f0.png)

**Comment by jeff30075** [comment]
It also shows in installed programs:
![image](https://user-images.githubusercontent.com/34559109/34054683-e3487522-e180-11e7-9f0a-c051218354f7.png)

**Comment by jeff30075** [comment]
As you can see from screenshot of programs also, it shows office 365.  Assuming that as the origin of my excel.

To answer your early question regarding the ?ActiveCell.PivotTable.PivotCache().OLAP.......it says True (see below)

![image](https://user-images.githubusercontent.com/34559109/34054823-634e8766-e181-11e7-8e67-8209f4baa754.png)

**Comment by jeff30075** [comment]
Hope that helps. if you need more info please let me know.  Again, many thanks.

**Comment by furmangg** [comment]
Stupid question. Did you reboot?

If you go to Manage: COM Add-ins dropdown in the Excel Options... Add-ins dialog and uncheck the other add-ins you have installed and restart Excel, does OLAP PivotTable Extensions now work?

**Comment by jeff30075** [comment]
yes

**Comment by jeff30075** [comment]
I tried the disable of all other add-ins and rebooted too, just to be sure...and here's what I see. Notice if have the OLAP tools, but not the "Disable Auto-Refresh" button:
![image](https://user-images.githubusercontent.com/34559109/34060404-6510bff8-e198-11e7-8c0a-777517074ed2.png)

**Comment by furmangg** [comment]
Great. Then it works. Which other add-in was the culprit? Is that other add-in something freely available I can test?

Disable Auto Refresh will only work on Power Pivot not SSAS pivots.
