### ISSUE TITLE
Extension doesn't work with Power BI Premium datasets

### ISSUE THREAD

**Issue by tate-bowman** [OlapPivotTableExtensions/OlapPivotTableExtensions#23]
This is an incredible extension, but unfortunately it doesn't appear to work with Power BI Premium datasets, which are exposed through the same XMLA protocol as Analysis Services Tabular.  I've used this extension against Tabular data sources before, but never against a Power BI dataset (until now).  I'm receiving a few different errors, but they appear to mostly revolve around authentication.  I received one error that said "The integrated security 'ClaimsToken' is not supported for native connections."  Perhaps the ADOMD.NET package needs updated for this support (since Power BI Premium XMLA is a rather new implementation)?  I'm happy to help test and work towards a solution!

![image](https://user-images.githubusercontent.com/34358237/69368879-938b6000-0c60-11ea-9ff5-d1d436814680.png)

**Comment by tate-bowman** [comment]
I just now tested a local Power BI dataset by connecting to the diagnostic port through the Analysis Services connector in Excel, and this extensions works flawlessly.  I think the errors purely boil down to authentication with the Power BI service.

**Comment by furmangg** [comment]
Thanks for reporting. I believe I just need to upgrade to the latest ADOMD.NET as part of the next release. Will keep this thread posted. I don’t have an immediate timeline on the next release. 

I can’t recall if I have tested whether Analyze in Excel works for Power BI Service in OLAP PivotTable Extensions. It uses a different approach that’s independent from XMLA endpoints if I recall. I don’t believe I have tested this and doubt it works yet. But try it

**Comment by tate-bowman** [comment]
Thanks! I haven’t tested Analyze in Excel either, but you’re correct it’s a different approach to the XMLA endpoint...like a private version of it. I’ll give it a test tomorrow and report back, but I don’t expect it will work either.

**Comment by tate-bowman** [comment]
Suspicions confirmed.  Analyze in Excel via Power BI doesn't work, either.  I'm hoping the latest ADOMD.NET dll will resolve these issues and that it's a relatively simple fix.

**Comment by furmangg** [comment]
[Release 0.9.6](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/latest) adds support for Power BI (both Analyze in Excel and the Power BI Premium XMLA endpoint). Please give it a try.

**Comment by tate-bowman** [comment]
Works for me now! Thanks @furmangg!!
