### ISSUE TITLE
Azure Analysis Service connection - filter returns error without VPN connection to cloud.

### ISSUE THREAD

**Issue by mnravihenkel** [OlapPivotTableExtensions/OlapPivotTableExtensions#27]
Hello Team,

OLAP Pivot Table Extension works fine with Azure Analysis Service when we use below connection string.
We use this connection in office or with VPN connection at home.

Provider=MSOLAP.8;Integrated Security=SSPI;Persist Security Info=True;Initial Catalog=CUBE;Data Source=asazure://westeurope.asazure.windows.net/INSTNACE;MDX Compatibility=1;Safety Options=2;MDX Missing Member Mode=Error;Update Isolation Level=2

Same report without VPN connection when we work from home returns below error message when  we try to filter the data.
Screenshot attached. Could you please advise ?

Connection string without VPN:

Provider=MSOLAP.8;Persist Security Info=True;User ID="";Initial Catalog=CUBE;Data Source=asazure://westeurope.asazure.windows.net/NISTANCE;MDX Compatibility=1;Safety Options=2;MDX Missing Member Mode=Error;Update Isolation Level=2

![OLAP filter error 2](https://user-images.githubusercontent.com/71008732/92582474-4b8e0600-f291-11ea-91d5-47a8912ae84e.JPG)
![OLAP Filter error 1](https://user-images.githubusercontent.com/71008732/92582475-4c269c80-f291-11ea-975a-2d956d3b7598.JPG)

**Comment by darealgoku** [comment]
any updates to this issue?

**Comment by furmangg** [comment]
I've updated to the latest Analysis Services driver and retested Azure Analysis Services connectivity/authentication in the latest release which is [Release 0.9.6](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/latest). Please give it a try. Write back if you're still having this issue.

**Comment by mnravihenkel** [comment]
Hello @furmangg 

Thanks for your support. I installed latest version and tested. It works as expected. 

Regards,
