### ISSUE TITLE
Can't filter with Power Bi Dataset Connection

### ISSUE THREAD

**Issue by GigaFluxx** [OlapPivotTableExtensions/OlapPivotTableExtensions#29]
I can't filter using a Power Bi Dataset connection. Not sure if there is a solution.

![image](https://user-images.githubusercontent.com/81186214/112039856-e017d180-8b1a-11eb-8a99-5c8551badbd9.png)

**Comment by samaguire** [comment]
Same problem

![image](https://user-images.githubusercontent.com/62320770/119429365-d00eaf00-bd62-11eb-9991-6d669e15050d.png)
![image](https://user-images.githubusercontent.com/62320770/119429380-d69d2680-bd62-11eb-8b66-c663905cd67e.png)

**Comment by Darryl284** [comment]
Hi, 

My organisation is facing the exact same issue when trying to connect to a Power BI dataset using the plugin.
Is there any solution available?

**Comment by BirdyLai** [comment]
Same issue here. Hey buddy, when do you think you can fix this and release a new version? Would much appreciate it.

**Comment by furmangg** [comment]
Power BI (both Analyze in Excel and Power BI Premium XMLA endpoints) are now supported in [Release 0.9.6](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/latest). Please give it a try.

**Comment by samaguire** [comment]
> Power BI (both Analyze in Excel and Power BI Premium XMLA endpoints) are now supported in [Release 0.9.6](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/latest). Please give it a try.

Works for me now 👍
