### ISSUE TITLE
Addin error on Excel startup

### ISSUE THREAD

**Issue by mjh7** [OlapPivotTableExtensions/OlapPivotTableExtensions#3]
I'm hoping someone can point me in the right direction on this - I found and downloaded version 0.9 and installed on Windows 7 for 64-bit Excel 2013. I then get the following error message on when starting Excel and have to uninstall the addin to remedy. It would be awesome if I can stop PowerPivot from recalculating everything every time I make a small change... thanks for developing this tool!

![olap pivottable extensions error 2](https://user-images.githubusercontent.com/34108681/33452315-b0d7086c-d5c6-11e7-8288-5dacf21b456b.JPG)

**Comment by furmangg** [comment]
What's the exact version number of Excel? I would like to check if there are updates available.

**Comment by mjh7** [comment]
Excel 2013 (15.0.4981.1000) part of Office Professional Plus 64-bit. Thanks for looking into it!

**Comment by furmangg** [comment]
Do you have any other add-ins installed? If so, can you temporarily disable those other add-ins to see if the behavior changes?

I haven't been able to reproduce yet.

**Comment by furmangg** [comment]
closing because I can't repro. if others have this issue please comment
