### ISSUE TITLE
v0.9.5 not supporting Excel 2016

### ISSUE THREAD

**Issue by ayockel** [OlapPivotTableExtensions/OlapPivotTableExtensions#30]
The documentation says v0.9.5 supports Excel 2016 but when I try to install I see this error

![thumbnail_image001](https://user-images.githubusercontent.com/8174802/123147117-a792d700-d42c-11eb-84d8-a0bd05c34f10.png)

How can I resolve this error?

Thanks

**Comment by furmangg** [comment]
Can you launch Excel and screenshot the File... About screen? Wondering whether you have 32-bit or 64-bit Excel 2016

**Comment by ayockel** [comment]
[cid:7ae496ca-b7ad-4843-a35f-e418b7facf3c]
________________________________

**Comment by furmangg** [comment]
You will have to upload it on the GitHub website. The image didn’t come through.

**Comment by ayockel** [comment]
![image](https://user-images.githubusercontent.com/8174802/123291978-9b685180-d4e0-11eb-9fdc-db541246407d.png)

**Comment by ayockel** [comment]
Any suggestions?

**Comment by furmangg** [comment]
Unfortunately I don’t. There is probably some check buried in the installer that I’m having trouble spotting despite studying it for 30 minutes. 

I will leave this open so I can look at this next time I’m am working on a newer build. No ETA. And honestly supporting a 5 year old version of Excel and 32-bit is pretty low on the priority list.

**Comment by ayockel** [comment]
Thanks

**Comment by furmangg** [comment]
Can you make sure you were trying to install 0.9.5. You might re-download from here and double check. I'm a bit surprised to see that error message:
https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/download/v0.9.5/OLAP.PivotTable.Extensions.Setup.v0.9.5.exe
