### ISSUE TITLE
New version of Azure Analysis Services client libraries needed

### ISSUE THREAD

**Issue by expertise-team** [OlapPivotTableExtensions/OlapPivotTableExtensions#31]
Dear Greg,

Microsoft has announced the following some time ago:

"Analysis Services client libraries version 19.12.3.0 or higher offers important security enhancements, so any applications that are still using earlier versions of the Analysis Services client libraries will not be supported after 30 June 2021."

Since the client libraries are necessary to change, it is not possible to use OlapPivotTableExtensions with Azure Analysis Services backend.

Are you planning to upgrade your solution with the newest ADOMD libraries so that the solution can be used?

Thank you very much for your response in advance,
Laszlo Meszaros

**Comment by furmangg** [comment]
Thanks for mentioning. Yes I intend on upgrading the version in the next release. I don’t have a date yet but will leave this open until that is released.

**Comment by expertise-team** [comment]
Thank you for your quick response. Do you have a commercial version of this extension or can we sponsor this project somehow?How can we help you to resolve this issue as soon as possible?

**Comment by furmangg** [comment]
Feel free to use the contact form and we can discuss:
https://olappivottableextensions.github.io/Contact

**Comment by furmangg** [comment]
I've updated to the latest Analysis Services client library on [nuget](https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.retail.amd64/) (which is currently 19.27.2.1) as part of [Release 0.9.6](https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/latest). Thanks for bringing this up!
