### ISSUE TITLE
Can't Filter List with Power BI Connection again

### ISSUE THREAD

**Issue by GigaFluxx** [OlapPivotTableExtensions/OlapPivotTableExtensions#35]
The Filter List feature was working fine after the previous update, however recently it stopped working again with the following error.
It says something about the login popup being cancelled but I selected my account as I always have and never cancelled it.

![image](https://user-images.githubusercontent.com/81186214/181308919-fcd8a60e-111c-4484-85d2-d13b9fa987da.png)
![image](https://user-images.githubusercontent.com/81186214/181308973-0c27a6cd-60f5-49de-a772-daae46410ade.png)
![image](https://user-images.githubusercontent.com/81186214/181309041-c333f7ea-8008-4074-b802-9cc124871447.png)

**Comment by furmangg** [comment]
On the About tab can you confirm you are running version 0.9.6?

Can you copy the connection string for your PivotTable? I want to make sure I distinguish between Analyze in Excel and XMLA endpoint.

**Comment by GigaFluxx** [comment]
Sure!

![image](https://user-images.githubusercontent.com/81186214/181349154-2cfc143e-bb24-489c-9e3e-58608423dcb6.png)

`Provider=MSOLAP.8;Integrated Security=ClaimsToken;Persist Security Info=True;Initial Catalog=sobe_wowvirtualserver-83e65052-0c8e-438a-8068-d8f16f58b4e9;Data Source=pbiazure://api.powerbi.com;MDX Compatibility=1;Safety Options=2;MDX Missing Member Mode=Error;Identity Provider=https://login.microsoftonline.com/common, https://analysis.windows.net/powerbi/api, 929d0ec0-7a41-4b1e-bc7c-b754a28bddcc;Update Isolation Level=2`

**Comment by cgholderfield** [comment]
I am seeing the same behavior with version 0.9.6.0 (32 bit).  Here's my connection string:

`Provider=MSOLAP.8;Integrated Security=ClaimsToken;Persist Security Info=True;Initial Catalog=sobe_wowvirtualserver-fa8c9133-39b4-4a46-a6bd-05c59f2d6d2a;Data Source=pbiazure://api.powerbi.com;MDX Compatibility=1;Safety Options=2;MDX Missing Member Mode=Error;Identity Provider=https://login.microsoftonline.com/common, https://analysis.windows.net/powerbi/api, 929d0ec0-7a41-4b1e-bc7c-b754a28bddcc;Update Isolation Level=2`

This dataset resides in a Power BI premium workspace.

**Comment by furmangg** [comment]
Thanks. I'll prioritize reproducing and fixing this bug for the next release. No ETA at the moment but I will update this thread. Thanks for reporting and sorry that it's currently broken.

**Comment by jaiken0704** [comment]
@furmangg do we have an ETA on a fix for this yet?  This is by far the most valuable tool I use in my everyday work.  :)

**Comment by furmangg** [comment]
I've got a beta build which fixes this issue. (The fix was forcing TLS1.2 around this bit of code.) Feel free to contact me if you want to be a beta tester:
https://olappivottableextensions.github.io/Contact

**Comment by furmangg** [comment]
This is now fixed in release 0.9.7
