### ISSUE TITLE
Problem Getting Power BI access Token

### ISSUE THREAD

**Issue by HippocratesHolding** [OlapPivotTableExtensions/OlapPivotTableExtensions#36]
Good evening,
we have installed Olap extension on office 365.
from the end of July the extension returns the error described in the title.
I am attaching images
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/112500136/187479212-751b5bfd-2a50-47a8-a20b-b0052942c692.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/112500136/187479216-572f7bc6-2653-445e-8d8b-e7373620ee35.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/112500136/187479219-aecbb1e4-8b96-4cda-aa4c-304e561a13ab.png)

**Comment by furmangg** [comment]
I've got a beta build which fixes this issue. (The fix was forcing TLS1.2 around this bit of code.) Feel free to contact me if you want to be a beta tester:
https://olappivottableextensions.github.io/Contact

**Comment by furmangg** [comment]
This is now fixed in the latest release 0.9.7
