### ISSUE TITLE
Cross Domain connections not working?

### ISSUE THREAD

**Issue by darkice83** [OlapPivotTableExtensions/OlapPivotTableExtensions#37]
We are setup where employees have work computers on Domain A, and contractors have their work computers on Domain B, but also have accounts on Domain A. (let's say they login to their machine with Domain B\username, and on Domain A they have user.name

When employees access SSAS through Excel, they use the integrated security method to connect to our Cubes, and when using the OlapPivotTableExtensions, everything works great.
For contractors, since their logged into their company's Domain B\username, when connecting to our SSAS server, they can't use integrated authentication, so they specify their Domain A\user.name along with password.
Using this method of authentication works when browsing the cubes, however when using OlapPivotTableExtensions, they get an error message
"A connection cannot be made. Ensure that the server is running. Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host."
Provider=MSOLAP.8;Persist Security Info=True;Initial Catalog=<ssas db name>;Data Source= <server name>;MDX Compatibility=1;Safety Options=2;MDX Missing Member Mode=Error;Subqueries=2;Update Isolation Level=2;LocaleIdentifier=1033;Applicatino Name=OLAP PivotTable Extensions v0.9.7.0 (64-bit)
16.0.43.20
<User path>\Microsoft.AnalysisServices.AdomdClient.dll
at
Microsoft.AnalysisServices.AdomdClient.XmlaClient.Connect(ConnectionInfo connectionInfo, Boolean beginSession)
at
Microsoft.AnalysisServices.AdomdClient.AdomdConnection.XmlaClientProvider.Connect()
at
Microsoft.AnalysisServices.AdomdClient.AdomdConnection.ConnectToXMLA(Boolean createSession, Boolean isHTTP)
at
Microsoft.AnalysisServices.AdomdClient.AdomdConnection.Open()
at
OlapPivotTableExtensions.MainForm.ConnectAdomdClientCube() in
C:\project\OlapPivotTableExtensions\Github\OlapPivotTableExtensions\MainForm.cs:line 878

(apologies for typos, they sent a screenshot and i tried to type it up as best as i could)

I tried looking at the code for MainForm.cs on line 878 and it failed at conncube.open() and I wasn't certain what caused the issue. However a few lines above there was a mention of "removing blank user ids and password" which, when looking at the connection string in the error, didn't have the User ID= line in it.
the connection string in Excel lists it as Provider=MSOLAP.8;Persist Security Info=True;User ID=Domain A\user.name;Initial Catalog=<ssas db name>..etc..

                        //remove blank user IDs and passwords from connection string which resolve an issue with AAS connections failing if either is blank
                        sConnectionString = sConnectionString.Replace(";Password=\"\"", "");
                        sConnectionString = sConnectionString.Replace(";Password=;", ";");
                        sConnectionString = sConnectionString.Replace(";User ID=\"\"", "");
                        sConnectionString = sConnectionString.Replace(";User ID=;", ";");
                        sConnectionString = sConnectionString.Replace(";User Id=\"\"", "");
                        sConnectionString = sConnectionString.Replace(";User Id=;", ";");
                        sConnectionString = sConnectionString.Replace(";user id=\"\"", "");
                        sConnectionString = sConnectionString.Replace(";user id=;", ";");
                        sConnectionString = sConnectionString.Replace(";Uid=\"\"", "");
                        sConnectionString = sConnectionString.Replace(";Uid=;", ";");
                        sConnectionString = sConnectionString.Replace(";uid=\"\"", "");
                        sConnectionString = sConnectionString.Replace(";uid=;", ";");

                        EnableStrongSecurityProtocol();
                        try
                        {
                            if (!bIsExcel15Model)
                            {
                                connCube = new AdomdConnection(sConnectionString, AdomdType.AnalysisServices);
                            }
                            else
                            {
                                connCube = new AdomdConnection(sConnectionString, AdomdType.Excel);
                            }
                            connCube.Open();
                        }

**Comment by furmangg** [comment]
When contractors create their connection to SSAS and put in a username and password on the first screen:
![specifying credentials on connection](https://user-images.githubusercontent.com/9261846/199616473-8406a2f0-44f8-4485-aa7b-130b61a3e02d.png)

They need to make sure to check these two checkboxes on the last screen.

![save password and always use connection](https://user-images.githubusercontent.com/9261846/199616360-c945a2ae-df7e-46b6-8c79-4d0c5cdbc79c.png)

That saves the password such that OLAP PivotTable Extensions is able to read it for impersonating that user so we can connect to the cube with the same credentials.

Please let me know if that resolves the problem.

**Comment by darkice83** [comment]
I got a response from our user that it worked! Thank you
