### ISSUE TITLE
register addin without vsto or installer

### ISSUE THREAD

**Issue by LogicBaer** [OlapPivotTableExtensions/OlapPivotTableExtensions#38]
Hello,

is it possible to register the addin without the installer and VSTO?
I have manually stored the entry for the addin in the registry and registered the dll using regasm. Nevertheless, there is always the message that the addin can not be loaded because an error occurs at runtime.

If you install it via VSTO it works. Does anyone have an idea what to do?

Sincerely

**Comment by furmangg** [comment]
I don't know the answer, but what are you trying to accomplish? If you're trying to run the installer silently, see this thread:
https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/issues/20#issuecomment-525911673

**Comment by LogicBaer** [comment]
I tried to make the addin available in Excel without an installer, using regasm and a registry entry I created myself.
I was just interested to see if it works that way.

Is also no matter have no desire to try further ^^

But you are right. Run the installer silent should be enough.
Thanks!
