### ISSUE TITLE
Excel startup error and add-in does not show

### ISSUE THREAD

**Issue by gtraub** [OlapPivotTableExtensions/OlapPivotTableExtensions#4]
Getting the following error on Excel 2013, 64bit, Windows7 startup and then the add-in does not display on right click. 

![olap_error](https://user-images.githubusercontent.com/16820850/33681146-5290f444-da89-11e7-9971-ae44a86d2f15.png)

**Comment by furmangg** [comment]
What's the exact version number of Excel? I would like to check if there are updates available. Did you try a repair on OLAP PivotTable Extensions? What version of my add-in are you running? Thanks for reporting.

**Comment by furmangg** [comment]
You are about 4 years behind on updates. Can you work on getting Excel updated and then try again?
https://support.office.com/en-us/article/Update-history-for-Office-2013-19214f38-85b7-4734-b2f8-a6a598bb0117

**Comment by gtraub** [comment]
Thanks for the help. We are going to upgrade her to 2016 so that should fix it.
