### ISSUE TITLE
Exception when choose "Show current filters" with Office 2007

### ISSUE THREAD

**Issue by fgonc124** [OlapPivotTableExtensions/OlapPivotTableExtensions#6]
Hi

I'm trying to use your addin with an Excel 2007 file whioch has a connection to an Ola server.

I installed version 0.8.4.0. When I choose "show current filters" I get an exception.

The same file with Office 2013 works fine.

How can I debug such problem.

I can't upgrade to 2013

The problem appears in Windows 7 , 8.1 and 10 with Office 2007

Thanks
![olapext_error](https://user-images.githubusercontent.com/26040543/35776933-523eaf98-099d-11e8-8c90-da8b7dfb56c3.JPG)
![olapext_error_00](https://user-images.githubusercontent.com/26040543/35776934-525f00fe-099d-11e8-8561-8305c24bcc83.JPG)
![olapext_error_02](https://user-images.githubusercontent.com/26040543/35776935-527c2d64-099d-11e8-8e9f-c06ac38aad2a.JPG)

**Comment by furmangg** [comment]
Although now that I read that documentation page more carefully I don't think that's the problem because it would have said "unsupported language configuration" if it was! Hmm. Can you review that page and let me know what you think?

**Comment by fgonc124** [comment]
Hi

Thank you for your reply.

All the machines I used were configured witjh english and also Office .

On the machine with 2013 I get this

[image: Imagem intercalada 1]

2018-02-04 13:47 GMT+00:00 furmangg <notifications@github.com>:

**Comment by fgonc124** [comment]
Hi again

I get this from a pc with 2007 . It has the same languages as the pc with
Office2013

[image: Imagem intercalada 1]

2018-02-04 13:47 GMT+00:00 furmangg <notifications@github.com>:

**Comment by fgonc124** [comment]
Hi again

The problem surges  on Mainform.c  on line   *field.CreatePivotFields();*

if (field.IncludeNewItemsInFilter == false)
            {

               * field.CreatePivotFields();*

                foreach (Excel.PivotField pivotField in field.PivotFields)



2018-02-04 13:50 GMT+00:00 furmangg <notifications@github.com>:

**Comment by furmangg** [comment]
Those images did not come through. Can you try again? Possibly replying to the email with attachments doesn't work 

That CreatePivotFields function is an Excel one

**Comment by fgonc124** [comment]
I used the source code provided in your site to debug. On 2007 I get an
exception always on that line,  *CreatePivotFields * .

I attached the images from 2007 and 2013

thanks

2018-02-04 16:53 GMT+00:00 furmangg <notifications@github.com>:

**Comment by furmangg** [comment]
Thanks for debugging. If you will look at the GitHub website you will see the attachments don't show up.

**Comment by fgonc124** [comment]
Well, I can see them using Goolge Chrome on Github

Anyway, on my last email I sent it as an attachement.

Fernando

2018-02-04 20:39 GMT+00:00 furmangg <notifications@github.com>:

**Comment by fgonc124** [comment]
![olapext_office2013](https://user-images.githubusercontent.com/26040543/35782311-ee3d9b52-09ed-11e8-9da5-ea0495780b7c.JPG)
![olapext_about_ofice2013_about](https://user-images.githubusercontent.com/26040543/35782312-ee595f5e-09ed-11e8-9ab2-defdd750c36b.JPG)
![olapext_error_about_office2007](https://user-images.githubusercontent.com/26040543/35782313-ee75d0bc-09ed-11e8-8360-1baeb51e42db.JPG)

**Comment by fgonc124** [comment]
The problem was solved after I removed Skype For Business 2016

http://www-01.ibm.com/support/docview.wss?uid=swg21992629

Thanks

**Comment by furmangg** [comment]
Wow. Thank you so much for posting this solution!!
