### ISSUE TITLE
Error message: App property was not recognized

### ISSUE THREAD

**Issue by cbracht** [OlapPivotTableExtensions/OlapPivotTableExtensions#7]
Hello,

currently we moved to Office 365 ProPlus (Version 1708) and if we try to filter by using the PivotTable Extensions the following error is thrown:

![image](https://user-images.githubusercontent.com/1489764/36789931-7edf2baa-1c93-11e8-8e39-062b6f05dcda.png)

After further analysis the connection string is responsible. We use the property "Application Name" for adding a name to the connection for use in e.g. SQL Profiler. In Office 365 ProPlus an additional property "App" is automatically generated and can't be removed from the connection string.

Connection string:
Provider=MSOLAP.8;Integrated Security=SSPI;Persist Security Info=True;Initial Catalog=Vertrieb_Cube;Data Source=SQLSSAS\ServerName;MDX Compatibility=1;Safety Options=2;MDX Missing Member Mode=Error;Application Name=Excel MS BI Vertrieb und Marketing DE;**App=Excel MS BI Vertrieb und Marketing DE**;Update Isolation Level=2

The PivotTable Extensions version used is 0.9.0.0 (32-bit).

Thank you in advance,
cbracht

**Comment by furmangg** [comment]
Thank you for reporting this. That's good to know the OLEDB driver that Excel uses will support the App connection string property but ADOMD.NET which my extension uses will not. I'll leave this open until I'm able to workaround this limitation. Obviously feel free to temporarily remove the App= section in the connection string if you need to use my extension in the meantime.

**Comment by cbracht** [comment]
The only workaround is to remove the "Application Name" property, as ist seems that the "App" property is derived automatically by Excel from the "Application Name" property.
It's not possible for me to remove the "App" property from the connection string as it automatically gets appended in the instant I press "Ok" after changing the connection string.
Thank you for your great work with your PivotTable Extensions!

**Comment by furmangg** [comment]
Apologies. I didn't get to this in the latest release. I will try to get to it in the next release.

Note to self that rbulka has already taken a shot at coding this and opened a pull request, which I unfortunately missed when testing this release. Here's the code change:
https://github.com/rbulka/OlapPivotTableExtensions/commit/7bf7732b2994a44f9083fa33344b01852371cc85

**Comment by furmangg** [comment]
This is now fixed in release 0.9.7
